services:
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      APP_ENV: prod
      APP_DEBUG: "0"
      DATABASE_URL: "sqlite:///%kernel.project_dir%/var/data/app.db"
      CORS_ALLOW_ORIGIN: "http://127.0.0.1:5173"
